// Code generated by ifacemaker; DO NOT EDIT.

package pet_store

import (
	"context"

	dbnotes "github.com/vburenin/ifacemaker/__fixtures__/1.nested-modules/input/dbgo/notes"
	dbpets "github.com/vburenin/ifacemaker/__fixtures__/1.nested-modules/input/dbgo/pets"
)

// Storage ...
type Storage interface {
	CreatePet(ctx context.Context, arg dbpets.CreatePetParams) (dbpets.Pet, error)
	DeletePet(ctx context.Context, id string) error
	GetPet(ctx context.Context, id string) (dbpets.Pet, error)
	ListPets(ctx context.Context) ([]dbpets.Pet, error)
	UpdatePetName(ctx context.Context, arg dbpets.UpdatePetNameParams) (dbpets.Pet, error)
	AddNote(ctx context.Context, arg dbnotes.AddNoteParams) (dbnotes.Note, error)
	GetNotes(ctx context.Context, petID string) ([]dbnotes.Note, error)
	GetNotesLimit(ctx context.Context, arg dbnotes.GetNotesLimitParams) ([]dbnotes.Note, error)
}
